name: Automated Maintenance
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: # Enables on-demand/manual triggering: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3
      - run: |
          latest=`curl -s https://api.github.com/repos/aws/serverless-application-model/releases/latest | jq -r .tag_name | cut -c 2-`
          sed -i -E "s/aws-sam-translator>=[0-9.]+/aws-sam-translator>=$latest/" setup.py
          pip install -e .
          rm -rf src/cfnlint/data/DownloadsMetadata/*
          cfn-lint --update-iam-policies
          cfn-lint --update-documentation
          scripts/update_specs_services_from_ssm.py
          scripts/update_specs_from_pricing.py
          scripts/update_serverless_aws_policies.py
          cfn-lint --update-specs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: |
            autogenerated maintenance
          delete-branch: true
          title: autogenerated maintenance
