name: Automated Maintenance
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: # Enables on-demand/manual triggering: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      -
        id: maintenance
        run: |
          latest_sam_cli=`curl -s https://api.github.com/repos/aws/aws-sam-cli/releases/latest | jq -r .tag_name | cut -c 2-`
          latest=`curl "https://pypi.org/pypi/aws-sam-cli/$latest_sam_cli/json" -s | jq -r '.info.requires_dist[] | select(contains("aws-sam-translator"))' | cut -c 23- | rev | cut -c 2- | rev`
          sed -i -E "s/aws-sam-translator>=[0-9.]+/aws-sam-translator>=$latest/" setup.py
          pip install -e .
          rm -rf src/cfnlint/data/DownloadsMetadata/*
          cfn-lint --update-iam-policies
          cfn-lint --update-documentation
          scripts/update_specs_services_from_ssm.py
          scripts/update_specs_from_pricing.py
          scripts/update_serverless_aws_policies.py
          cfn-lint --update-specs
          echo "specversion=$(jq -r .ResourceSpecificationVersion src/cfnlint/data/CloudSpecs/us-east-1.json)" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: |
            Update CloudFormation specs to ${{ steps.maintenance.outputs.specversion }}
          body: |
            - Update CloudFormation specs to ${{ steps.maintenance.outputs.specversion }}
            - Update Specs from pricing data as of ${{ steps.maintenance.outputs.date }}

            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          delete-branch: true
          title: chore(specs) - Update CloudFormation specs to ${{ steps.maintenance.outputs.specversion }}
